builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    main: ./
    ldflags:
      - -s -w

archives:
  - format: tar.gz
    files:
      - LICENSE

dockers:
- image_templates:
  - &amd_image 'ghcr.io/odyfey/tern:{{ .Tag }}-amd64'
  use: buildx
  build_flag_templates:
  - "--push"
  - "--platform=linux/amd64"
- image_templates:
  - &arm_image 'ghcr.io/odyfey/tern:{{ .Tag }}-arm64'
  use: buildx
  build_flag_templates:
  - "--push"
  - "--platform=linux/arm64"
  goarch: arm64

docker_manifests:
- name_template: 'ghcr.io/odyfey/tern:{{ .Tag }}'
  image_templates:
    - *amd_image
    - *arm_image
- name_template: 'ghcr.io/odyfey/tern:latest'
  image_templates:
    - *amd_image
    - *arm_image