alterations:
  table: tern_alterations
  column: version
definitions:
  table: tern_definitions
environments:
  development:
    adapter: postgres
    database: tern_spec_development
  test:
    adapter: postgres
    database: tern_spec_test
  production:
    adapter: postgres
    database: tern_spec_production
