alterations:
  table: tern_alterations
  column: version
definitions:
  table: tern_definitions
environments:
  development:
    adapter: postgres
    database: tern_test_development
  test:
    adapter: postgres
    database: tern_test_test
  production:
    adapter: postgres
    database: tern_test_production
